plugins {
    id 'java'
}

group = 'myrobot'
version = '1.0'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(16)
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation files('C:/robocode/libs/robocode.jar')

    // DL4J core
    implementation 'org.deeplearning4j:deeplearning4j-core:1.0.0-M2.1'
    implementation 'org.nd4j:nd4j-native-platform:1.0.0-M2.1'

    // Lombok runtime classes needed by DL4J
    implementation 'org.projectlombok:lombok:1.18.32'

    // Add SLF4J Simple logger (1.7.x works best with DL4J M2.1)
    implementation 'org.slf4j:slf4j-simple:1.7.30'

    implementation 'javax.xml.bind:jaxb-api:2.3.1'
    implementation 'org.glassfish.jaxb:jaxb-runtime:2.3.1'
}


jar {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE

    from {
        configurations.runtimeClasspath.collect { it.isDirectory() ? it : zipTree(it) }
    }

    from(sourceSets.main.resources)
}
